version: "3.9"
services:
  kafka:
    image: docker-proxy.tcsbank.ru/bitnami/kafka:latest
    ports:
    - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"

  #
  zookeeper:
    image: docker-proxy.tcsbank.ru/bitnami/zookeeper:latest
    ports:
    - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  my-app:
    build:
      context: ./